steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['install', '.']
  env: ['PROJECT_ROOT=myapp']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp', '.']
images: ['gcr.io/$PROJECT_ID/myapp']